### ISSUE TITLE
Actions Not Working for Me At All - Newbie to Actions

### ISSUE THREAD

**Issue by jotasprout** [JF002/Pinetime#65]
I have no idea what to even say or where to start so I'll just say I've tried multiple times and these are the screenshots I have. Hopefully, they'll be more helpful than I am. I have no idea which ones will or will not be helpful.

![2020-09-19-163357_1920x1080_scrot](https://user-images.githubusercontent.com/12866150/94171503-5a62e400-fe5f-11ea-8d53-59259294dbb5.png)
![2020-09-19-163412_1920x1080_scrot](https://user-images.githubusercontent.com/12866150/94171507-5b941100-fe5f-11ea-8ff8-b6807ed7790b.png)
![2020-09-19-164925_1920x1080_scrot](https://user-images.githubusercontent.com/12866150/94171510-5c2ca780-fe5f-11ea-9895-2bc1e454e7ce.png)
![2020-09-19-165134_1920x1080_scrot](https://user-images.githubusercontent.com/12866150/94171516-5d5dd480-fe5f-11ea-8614-e73abcd4675e.png)
![2020-09-19-165141_1920x1080_scrot](https://user-images.githubusercontent.com/12866150/94171517-5df66b00-fe5f-11ea-9066-ab378b2df904.png)
![2020-09-19-165222_1920x1080_scrot](https://user-images.githubusercontent.com/12866150/94171519-5df66b00-fe5f-11ea-9aa7-f07a27538366.png)
![2020-09-19-165629_1920x1080_scrot](https://user-images.githubusercontent.com/12866150/94171520-5df66b00-fe5f-11ea-8b8d-6acdc7ffd76e.png)
![2020-09-19-165646_1920x1080_scrot](https://user-images.githubusercontent.com/12866150/94171522-5e8f0180-fe5f-11ea-8175-503f74076d56.png)
![2020-09-19-165738_1920x1080_scrot](https://user-images.githubusercontent.com/12866150/94171524-5e8f0180-fe5f-11ea-8ba0-42cd50aa2293.png)
![2020-09-19-165809_1920x1080_scrot](https://user-images.githubusercontent.com/12866150/94171527-5e8f0180-fe5f-11ea-95c1-2c4a7061ea31.png)

**Comment by lupyuen** [comment]
Hi: Sorry for the delay... The error in the log is this...

https://github.com/jotasprout/Pinetime/runs/1138700180?check_suite_focus=true

```
/home/runner/work/Pinetime/Pinetime/src/drivers/TwiMaster.cpp:1:10: fatal error: sdk/integration/nrfx/nrfx_log.h: No such file or directory
 #include <sdk/integration/nrfx/nrfx_log.h>
```

Could you please edit...

https://github.com/jotasprout/Pinetime/blob/master/src/drivers/TwiMaster.cpp

And change the first 2 lines from

```c
#include <sdk/integration/nrfx/nrfx_log.h>
#include <sdk/modules/nrfx/hal/nrf_gpio.h>
```

To...

```c
#include <nrfx_log.h>
#include <nrf_gpio.h>
```

And it should work, hopefully.

I wrote about this bug here...

https://lupyuen.github.io/pinetime-rust-mynewt/articles/cloud#our-first-pinetime-firmware-build

Under the section "4. Our First PineTime Firmware Build", paragraph "If we see this error...". 

I'm terribly sorry my instructions were not clear, please let me know whether this fixes the build. Thanks.

**Comment by jotasprout** [comment]
Your instructions were clear. I just didn't see the error when I was looking because it was deep into that line.
